package com.opuscapita.demo.error;

import org.springframework.boot.web.servlet.error.ErrorController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import springfox.documentation.annotations.ApiIgnore;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@ApiIgnore
@RestController
public class AppErrorController implements ErrorController {

    private static final String ERROR_PATH = "/error";
    public static final String ERROR_RESPONSE_ATTR = AppErrorController.class.getName();

    @RequestMapping(value = ERROR_PATH)
    public ErrorResponseDto handleError(HttpServletRequest request, HttpServletResponse response) {
        Object appErrorDto = request.getAttribute(ERROR_RESPONSE_ATTR);

        if (appErrorDto != null && appErrorDto instanceof ErrorResponseDto) {
            // This error was generated in a REST controller
            // so we are just passing it.
            return (ErrorResponseDto) appErrorDto;
        } else {
            // This error was generated by a web containter or Spring Framework
            // outside of REST controller method.
            return new ErrorResponseDto("Error #" + response.getStatus());
        }
    }
}
